Update info.json
axtox/exoskeleton-mark-ii pull request #2
Opened 2019-06-18 03:08 UTC by PaladinFallen

2019-07-03 20:33 UTC, axtox requested changes
See comments in 'files' section. Make changes in order to merge this pull request

2019-07-03 20:33 UTC, axtox commented on info.json
> +  "version": "3.1.0",
the versioning guideline tells that if the application was changed in the way that it becomes incompatible with previus version, you need you change the major number. This is our case, so I suggest to change version to 4.0.0

2019-07-04 14:10 UTC, PaladinFallen commented
I made the fixes to the files, so everything is good.

2019-07-05 18:30 UTC, axtox approved these changes
Okay, now it aligned with guidelines! Thank you!

2019-07-05 18:30 UTC, merged