Update item.lua
axtox/exoskeleton-mark-ii pull request #4
Opened 2019-06-18 03:10 UTC by PaladinFallen

2019-07-03 20:32 UTC, axtox requested changes
Make prior changes to merge this pull request! See comments in "files" section

2019-07-03 20:32 UTC, axtox commented on prototypes/item/item.lua
> +		--flags = { "goes-to-quickbar" },
you can safely remove this code line, i've tested it - works fine without it

2019-07-04 14:10 UTC, PaladinFallen commented
I made the fixes to the files, so everything is good.

2019-07-05 18:29 UTC, axtox approved these changes
Okay, now it can be merged! Thanks!

2019-07-05 18:30 UTC, merged